### ISSUE TITLE
apt-repos should use the APT_CONFIG environment variable

### ISSUE THREAD

**Issue by pabs3** [chrlutz/apt-repos#3]
I noticed that apt-repos doesn't use the APT_CONFIG environment variable. If you peruse the apt.conf(5) manual page (quoted below) you will see that in order to decouple apt from the system apt config in /etc/apt/ you need to set the APT_CONFIG environment variable to the name of an apt config file and set the Dir option in that file. If you do not do that, then things like apt hooks and other stuff will leak into your separate apt rootdir, which it seems like one would not want to happen for apt-repos setup. Other tools that avoid this by using APT_CONFIG include chdist (from devscripts), the apt-venv package and the derivatives census.

```
       When an APT tool starts up it will read the configuration files in the following order:

        1. the file specified by the APT_CONFIG environment variable (if any)
        2. all files in Dir::Etc::Parts ...
        3. the main configuration file specified by Dir::Etc::main
```

**Comment by chrlutz** [comment]
Thanks for pointing that out! This could explain some strange effects I already noticed when using apt-repos on different systems (e.g. debian vs. ubuntu). I will have a look at this.

**Comment by chrlutz** [comment]
Fixed in current master d77bdc3550a313cb2cd3642ce63812e3a6780d3br .

Tested the following way:

sudo vim /etc/apt/apt.conf.d/16gruetze # set some invalid (syntax error) content, such as "grütze"
sudo apt update # to confirm system's apt update now fails
bin/apt-repos # --> doesn'f fail, so it's no longer using systems apt config

**Comment by pabs3** [comment]
On Wed, 2020-08-12 at 09:31 -0700, Christoph Lutz wrote:

> Fixed in current master d77bdc3550a313cb2cd3642ce63812e3a6780d3br .

Looks good. BTW, style tip, you can do this instead of using string
concatenation and it is much more readable (and shorter):

__defaultBaseDirs = [ expanduser('~/.config/apt-repos'), expanduser('~/.apt-repos'), '/etc/apt-repos' ]
__defaultCacheDir = expanduser('~/.cache/apt-repos')

-- 
bye,
pabs

https://wiki.debian.org/PaulWise
